name: Create Release

on: 
  push:
    tags:
    - '*'
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build MIS
      run: mvn -Dtest=AllTestsNoChrX install
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "target/imputationserver.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
